name: PR Comment
run-name: Commenting on PR with check results 💬

on:
  workflow_run:
    workflows: ["Pull Request Check"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Download PR info
        uses: actions/download-artifact@v4
        with:
          name: pr-info
          path: ./pr-info/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Read PR info
        id: pr_info
        run: |
          pr_number=$(cat ./pr-info/pr_number)
          success=$(cat ./pr-info/success)
          run_id=$(cat ./pr-info/run_id)
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "success=$success" >> $GITHUB_OUTPUT
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
          
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ steps.pr_info.outputs.success }}' === 'true';
            const workflowConclusion = '${{ github.event.workflow_run.conclusion }}';
            const runId = '${{ steps.pr_info.outputs.run_id }}';
            
            let message;
            if (workflowConclusion === 'success' && success) {
              message = '✅ **Compilation Check Passed** \n\n`compile_map.py` ran successfully without errors. Both map and bar chart files were generated correctly. The code is ready to be merged.';
            } else if (workflowConclusion === 'failure') {
              message = `❌ **Compilation Check Failed** \n\n\`compile_map.py\` encountered errors during execution. Please check your code changes. See [Action logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${runId}) for details.`;
            } else {
              message = `⚠️ **Compilation Check Completed with Issues** \n\nThe workflow completed but there may have been issues. Please check the [Action logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${runId}) for details.`;
            }
            
            github.rest.issues.createComment({
              issue_number: ${{ steps.pr_info.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });